name: artifact-management

on:
  workflow_call:

jobs:
  artifact-management:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: .

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::070410680102:role/github-role
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'
        
    # - name: Configure AWS CLI with SSO
    #   run: |
    #     aws configure sso --start-url https://quind.awsapps.com/start# --region us-east-1
    #     aws sso login --account-id 0704-1068-0102 

    # - name: Login to Amazon ECR
    #   run: |
    #     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 070410680102.dkr.ecr.us-east-1.amazonaws.com
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}



