on:
  workflow_call:
    inputs:
      semVer:
        description: 'Semantic Versioning'
        required: true
        type: string

jobs:
  delete-branch-release:
    runs-on: ubuntu-latest
    name: delete release
    env:
      run_id: ${GITHUB_RUN_ID}
    steps:
      - name: Checkout to project repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
      - name: delete-release
        run: |
          curl -s -X DELETE -u username:${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/${{ github.repository }}/git/refs/heads/release/${{ inputs.semVer }}-${{ env.run_id }}