name: development integration

on:
  workflow_call:
    outputs:
    SemVer:
      description: "Versionamiento semantico"
      value: ${{jobs.version.outputs.SemVer}}


jobs:
  version:
    name: versionamiento semantico
    uses: ./.github/workflows/semantic-versioning.yml
    secrets: inherit

  build-react:
    needs: version 
    name: Build angular
    uses: ./.github/workflows/build-react.yml
    secrets: inherit
  


 

  
    

   

      


