name: pipeline-template

on: 
  workflow_call:
    outputs: 
      semVer: 
        description: "job1"
        value: ${{ jobs.development-integration.outputs.semVer }}

    
jobs:
  development-integration: 
    name: development_integration
    uses: ./.github/workflows/development_integration.yml
    secrets: inherit
  artifact-management:
    needs: development-integration
    name: artifact-management
    uses: ./.github/workflows/artifact_management.yml
    with:
      semVer: ${{ needs.development-integration.outputs.semVer }}
    secrets: inherit

 
      



      

      
        
      

  
  
