name: pipeline-template

on: 
  workflow_call:
    outputs:
        semver:
          description: "versionamiento semantico"
          value: ${{ jobs.development-integration.outputs.semver }}
    
    
jobs:
  development-integration: 
    name: development_integration
    uses: ./.github/workflows/development_integration.yml
    secrets: inherit
  artifact-management:
    needs: development-integration
    name: artifact-management
    uses: ./.github/workflows/artifact_management.yml
    with:
      semver: ${{ needs.development-integration.outputs.semver }}
    secrets: inherit

 
      



      

      
        
      

  
  
