name: pipeline-template

on: 
  workflow_call:
    outputs:
      semv:
        description: 'semantic version'
        value: ${{ jobs.version.outputs.semv }}
jobs:
  development-integration: 
    name: development_integration
    uses: ./.github/workflows/development_integration.yml
    secrets: inherit
  artifact-management:
    needs: development-integration
    name: artifact-management
    uses: ./.github/workflows/artifact_management.yml
    secrets: inherit

 
      



      

      
        
      

  
  
