name: pipeline-template

on: 
  workflow_call:
    
jobs:
  development-integration:
    if:  github.ref_name == 'main'  
    name: development_integration
    uses: ./.github/workflows/development_integration.yml
    secrets: inherit

 
      



      

      
        
      

  
  
