on:
  workflow_call:
    inputs:
      semVer:
        description: 'Semantic Versioning'
        required: true
        type: string
      target_branch: 
        description: 'target branch'
        required: true
        type: string
jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    name: auto-pull-request
    steps:
    - name: Checkout to project repository 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: ${{ github.repository }}
        ref: ${{ github.ref_name }}

    - name: Action pull request
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ secrets.TOKEN_TEMPLATE }}
        source_branch: ${{ github.ref_name }}
        target_branch: ${{ inputs.target_branch }}
        title: auto pull request to ${{ inputs.target_branch }}
        body: "**Automated pull request **"
        reviewer: ${{ vars.REVIEWER}}
        new_string: ${{ github.event.commits[0].message }}
        get_diff: true