name: integration test
on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: f2x-flypass/${{ vars.INTEGRATION_REPOSITORY }}
          token: ${{ secrets.TOKEN_TEMPLATE }} # `GH_PAT` is a secret that contains your PAT

      - name: Configurar AWS CLI Production 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CER }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} 
          
      - name: autenticación RDS        
        run: |
            myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
            aws ec2 authorize-security-group-ingress --group-id sg-01996e047ba71c92c --protocol tcp --port 1521 --cidr ${myip}/32
            
      - name: rename environment file
        run: |
          mv .env.template .env
  
      - name: Environment Variables QA
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["**/.env"]'
        env:
          AWS_ACCESS: "${{ secrets.AWS_ACCESS_KEY_ID_CER }}"
          AWS_SECRET: "${{ secrets.AWS_SECRET_ACCESS_KEY_CER }}"
          AWS_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"
          QADB_USER: "${{ secrets.QADB_USER }}"
          QADB_PASS: "${{ secrets.QADB_PASS }}"
          URL_DB_CERT: "${{ vars.URL_DB_CERT2 }}" 

      - run: cat .env

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: npm install
        run: |
          npm install
      - name: Run success case
        run: |
          npm run ${{ vars.RUN_UI_TEST }}
      - name: Run publish Cucumber Report
        run: |
          npm run test
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "jsonlogs/**.json"
      - name: Publish cucumber report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Report-integration
          path: ./reports
          retention-days: 1
      - name: logout RDS 
        if: success() || failure()       
        run: |
           myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
           aws ec2 revoke-security-group-ingress --group-id sg-01996e047ba71c92c --protocol tcp --port 1521 --cidr ${myip}/32
              
