on:
  workflow_call:
jobs:
  shiftleft-security:
    runs-on: ubuntu-latest
    name: shiftleft-security
    steps:
      - name: Checkout to project repository 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
      
      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_TEMPLATE }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports
      
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ShiftLeftSecurity
          path: ./reports