name: semantic-versioning

on:
  workflow_call:
    inputs:
      dry_run:
        description: 'dry-run'
        required: true
        type: boolean
      bump:
        description: 'incremento'
        required: true
        type: string
    outputs:
      semVer:
        description: "Semantic Versioning"
        value: ${{ jobs.semantic-versioning.outputs.semVer }}
      
       
jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    env:
      run_id: ${GITHUB_RUN_ID}
    outputs:
      semVer: ${{ steps.tagger.outputs.new_version }}
    steps:

    - name: Checkout to project repository 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN_TEMPLATE }} # `GH_PAT` is a secret that contains your PAT
        ref: ${{ github.ref_name }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          repository: f2x-flypass/pipeline-templates
          token: ${{ secrets.TOKEN_TEMPLATE }}
          path: 'template'
          ref: 'main'

    - name: GitHub Tag feature develop release
      id: tagger
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run:  ${{ inputs.dry_run }}
        release_branches: feature/*,develop,release/*,main,hotfix*
        default_bump: ${{ inputs.bump }}

   
            
      

   
    
