name: semantic-versioning

on:
  workflow_call:   

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to project repository 
      uses: actions/checkout@v3

    - name: GitHub Tag 
      id: tagger
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run:  false
        release_branches: feature/*,main
        default_bump: minor


  
