name: semantic-versioning

on:
  workflow_call:   

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to project repository 
      uses: actions/checkout@v3

    - name: GitHub Tag 
      id: tagger
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.TOKEN_TALLER }}
        dry_run:  false
        release_branches: feature/*,main
        default_bump: minor

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: VersionConfig.yml

    - name: Display GitVersion outputs (step output)
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"